spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/h2db
    data-username: h2sa
    data-password: admin
    driver-class-name: org.h2.Driver
server:
  port: 9000
